<?php
// $Id$

/*
 * Implementation of hook_homebox()
 * 
 * @return
 *   An array of homebox page settings arrays.
 *   The machine name is specified in the array key. 
 *   The machine name and path MUST not be in use.
 * 
 * --------------------------------------------------
 *   The menu might need to be rebuilt / cache cleared in order for 
 *   pages in code to show on the Home Box admin page and become
 *   accessible via the specified path.
 * 
 *   Once an admin saves settings for a page in code, it resides
 *   in the database, and the code is no longer read, until it's
 *   reverted/deleted.
 */
function homebox_example_homebox() {
  $pages = array();
  
  $pages['testbox'] = array(
    'title' => 'Test Home Box',
    'path' => 'testbox',
    'menu' => 1,
    'enabled' => 1,
    'regions' => 3,
    'cache' => 0,
    'full' => 0,
    'roles' => array(
      0 => 'authenticated user',
    ),
    'color' => 1,
    'colors' => array(
      0 => '#e4f0f8',
      1 => '#c4d5b4',
      2 => '#ecc189',
      3 => '#ec8989',
      4 => '#6b6b70',
      5 => '#4b97e5',
    ),
    'blocks' => array(
      'node_0' => array(
        'module' => 'node',
        'delta' => '0',
        'region' => 1,
        'movable' => 1,
        'status' => 1,
        'open' => 1,
        'closable' => 1,
        'title' => '',
        'weight' => -8,
      ),
      'user_2' => array(
        'module' => 'user',
        'delta' => '2',
        'region' => 1,
        'movable' => 1,
        'status' => 1,
        'open' => 1,
        'closable' => 1,
        'title' => '',
        'weight' => -7,
      ),
      'user_1' => array(
        'module' => 'user',
        'delta' => '1',
        'region' => 3,
        'movable' => 1,
        'status' => 1,
        'open' => 1,
        'closable' => 1,
        'title' => '',
        'weight' => -7,
      ),
      'system_0' => array(
        'module' => 'system',
        'delta' => '0',
        'region' => 2,
        'movable' => 1,
        'status' => 1,
        'open' => 1,
        'closable' => 1,
        'title' => '',
        'weight' => -7,
      ),
      'user_3' => array(
        'module' => 'user',
        'delta' => '3',
        'region' => 2,
        'movable' => 1,
        'status' => 1,
        'open' => 1,
        'closable' => 1,
        'title' => '',
        'weight' => 1,
      ),
    ),
  );
  
  return $pages; 
}
